[package]
name = "jirust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
serde_with = { version = "1.4.0", features = ["json"]}

crossterm = "0.25.0"

tui = "0.19.0"

reqwest = "0.11.11"

futures = "0.3"

tokio = { version = "1.12.0", features = ["full"] }
# sqlite = "0.30.3"
serde-aux = "4.1.2"
surrealdb = "1.0.0-beta.8"
log = "0.4.17"
fern = "0.6.1"
chrono = "0.4.23"
anyhow = "1.0.68"
async-trait = "0.1.64"
# async-recursion = "1.0.0"
# rusqlite = "0.28.0"
