---
name: Publish

on:
  pull_request: {}

env:
  CARGO_TERM_COLOR: always

permissions:
  actions: read
  pull-requests: write
  id-token: read
  contents: read

jobs:
  style:
    name: Check Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - run: cargo fmt --all --check
