---
name: Publish

on:
  pull_request: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  style:
    name: Check Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - run: cargo fmt --all --check
  cargo_bump:
    name: Bump cargo version
    needs:
      - style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable

      - name: install cargo-bump
        run: cargo install cargo-bump

      - name: cargo bump
        run: cargo bump $(git describe --tags --abbrev=0)

      - name: Commit cargo.toml
        run: |
          git config --global user.name 'GITHUB ACTIONS USER'
          git config --global user.email 'github-actions-user@users.noreply.github.com'
          git commit -am "Automated cargo committed"
          git push
