---
name: Publish

on:
  push:
    tags:
      - "*"
env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.AUTO_ACTION }}

jobs:
  crates_io_publish:
    name: Publish (crates.io)

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: cargo-release Cache
        id: cargo_release_cache
        uses: actions/cache@v3
        with:
          path: ~/.cargo/bin/cargo-release
          key: ${{ runner.os }}-cargo-release

      - run: cargo install cargo-release
        if: steps.cargo_release_cache.outputs.cache-hit != 'true'

      - name: cargo login
        run: cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: cargo build
        run: cargo build --release --all-targets

      - name: cargo publish
        run: cargo publish --config 'package.version="$(git describe --tags --abbrev=0)"'

  github_release:
    needs:
      - crates_io_publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "jirust"
